services:
  - type: web
    name: ROM Peerbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
        sync: false
      - key: DEFAULT_CITY
        value: Singapore
      - key: DEFAULT_COUNTRY
        value: Singapore
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    healthCheckPath: /
